### ISSUE TITLE
Is it possible to do conversion in reverse?

### ISSUE THREAD

**Issue by nikolay-ulyanov** [SudoMaker/adlib2vgm#5]
Hi! Let's say I have adlib music file in vgm format, is it possible to convert it back to some adlib tracker format, e. g., to a2m?

**Comment by LTVA1** [comment]
No, VGM is register dump and a2m is a tracker format with patterns, effects and instrument macros. With rather complex algorithm you can come somewhat close but it won't be a guaranteed 1:1 conversion in general case

**Comment by nikolay-ulyanov** [comment]
Thanks for reply, I'll close the issue then
